-- CreateTable
CREATE TABLE `oper_brandstof` (
    `ID` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `LID_ID` MEDIUMINT UNSIGNED NOT NULL,
    `NAAM` VARCHAR(255) NOT NULL,
    `TIJDSTIP` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `BRANDSTOF_TYPE_ID` MEDIUMINT UNSIGNED NULL,
    `PRIJS` FLOAT NULL,
    `BEDRAG` FLOAT NULL,
    `LITERS` FLOAT NULL,
    `EXT_REF` VARCHAR(50) NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `oper_brandstof_VERWIJDERD_idx`(`VERWIJDERD`),
    INDEX `oper_brandstof_TIJDSTIP_idx`(`TIJDSTIP`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_winterwerk` (
    `ID` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `AANVANG` TIME NOT NULL,
    `EINDE` TIME NOT NULL,
    `OPMERKINGEN` VARCHAR(191) NULL,
    `LID_ID` MEDIUMINT UNSIGNED NOT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `oper_winterwerk_VERWIJDERD_idx`(`VERWIJDERD`),
    INDEX `oper_winterwerk_DATUM_idx`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_brandstof` ADD CONSTRAINT `oper_brandstof_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_brandstof` ADD CONSTRAINT `oper_brandstof_BRANDSTOF_TYPE_ID_fkey` FOREIGN KEY (`BRANDSTOF_TYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_winterwerk` ADD CONSTRAINT `oper_winterwerk_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
