-- CreateTable
CREATE TABLE `oper_daginfo` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VELD_ID` INTEGER NOT NULL,
    `BAAN_ID` INTEGER NOT NULL,
    `STARTMETHODE_ID` INTEGER NOT NULL,
    `VELD_ID2` INTEGER NOT NULL,
    `BAAN_ID2` INTEGER NOT NULL,
    `STARTMETHODE_ID2` INTEGER NOT NULL,
    `CLUB_BEDRIJF` BOOLEAN NOT NULL DEFAULT false,
    `DDWV` BOOLEAN NOT NULL DEFAULT false,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_winterwerk` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `AANVANG` TIME NOT NULL,
    `EINDE` TIME NOT NULL,
    `OPMERKINGEN` VARCHAR(191) NULL,
    `LID_ID` INTEGER NOT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `DATUM`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_VELD_ID_fkey` FOREIGN KEY (`VELD_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_BAAN_ID_fkey` FOREIGN KEY (`BAAN_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_STARTMETHODE_ID_fkey` FOREIGN KEY (`STARTMETHODE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_VELD_ID2_fkey` FOREIGN KEY (`VELD_ID2`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_BAAN_ID2_fkey` FOREIGN KEY (`BAAN_ID2`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_STARTMETHODE_ID2_fkey` FOREIGN KEY (`STARTMETHODE_ID2`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_winterwerk` ADD CONSTRAINT `oper_winterwerk_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
