-- CreateTable
CREATE TABLE `RefTypesGroepen` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(10) NULL,
    `EXT_REF` VARCHAR(25) NULL,
    `OMSCHRIJVING` VARCHAR(75) NOT NULL,
    `SORTEER_VOLGORDE` TINYINT NULL,
    `READ_ONLY` TINYINT NOT NULL DEFAULT 0,
    `BEDRAG_EENHEDEN` TINYINT NOT NULL DEFAULT 0,
    `VERWIJDERD` TINYINT NOT NULL DEFAULT 0,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
