version: "3.8"

services:
  helios-database:
    image: mariadb:latest
    container_name: helios-database
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: helios
    ports:
      - "3306:3306"