-- CreateTable
CREATE TABLE `oper_progressie` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LID_ID` INTEGER NOT NULL,
    `INSTRUCTEUR_ID` INTEGER NOT NULL,
    `COMPETENTIE_ID` INTEGER NOT NULL,
    `INGEVOERD` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `GELDIG_TOT` DATE NULL,
    `SCORE` INTEGER NULL,
    `OPMERKING` TEXT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `oper_progressie_VERWIJDERD_idx`(`VERWIJDERD`),
    INDEX `oper_progressie_LID_ID_idx`(`LID_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_progressie` ADD CONSTRAINT `oper_progressie_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_progressie` ADD CONSTRAINT `oper_progressie_INSTRUCTEUR_ID_fkey` FOREIGN KEY (`INSTRUCTEUR_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_progressie` ADD CONSTRAINT `oper_progressie_COMPETENTIE_ID_fkey` FOREIGN KEY (`COMPETENTIE_ID`) REFERENCES `ref_competenties`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
