-- AlterTable
ALTER TABLE `oper_daginfo` MODIFY `VELD_ID` INTEGER NULL,
    MODIFY `BAAN_ID` INTEGER NULL,
    MODIFY `STARTMETHODE_ID` INTEGER NULL,
    MODIFY `BAAN_ID2` INTEGER NULL,
    MODIFY `STARTMETHODE_ID2` INTEGER NULL;
