/*
  Warnings:

  - You are about to alter the column `VERWIJDERD` on the `oper_aanwezig_vliegtuigen` table. The data in that column could be lost. The data in that column will be cast from `TinyInt` to `UnsignedTinyInt`.
    - Checked OK ✅
  - You are about to alter the column `VERWIJDERD` on the `oper_brandstof` table. The data in that column could be lost. The data in that column will be cast from `TinyInt` to `UnsignedTinyInt`.
    - Checked OK ✅
  - You are about to alter the column `WINTER_WERK` on the `oper_rooster` table. The data in that column could be lost. The data in that column will be cast from `TinyInt` to `UnsignedTinyInt`.
    - Checked OK ✅
  - You are about to drop the column `BETAAL_URL` on the `oper_transacties` table. All the data in the column will be lost.
    - Checked OK ✅
  - You are about to alter the column `VERWIJDERD` on the `oper_winterwerk` table. The data in that column could be lost. The data in that column will be cast from `TinyInt` to `UnsignedTinyInt`.
    - Checked OK ✅
  - You are about to drop the column `BLOK_ID` on the `ref_competenties` table. All the data in the column will be lost.
    - This is renamed to `OUDER_ID` with data migration ✅
  - You are about to drop the column `ONDERWERP` on the `ref_competenties` table. All the data in the column will be lost.
    - This is renamed to `OMSCHRIJVING` with data migration ✅
  - You are about to alter the column `TRAINER` on the `ref_vliegtuigen` table. The data in that column could be lost. The data in that column will be cast from `TinyInt` to `UnsignedTinyInt`.
    - Checked OK ✅
  - Added the required column `OMSCHRIJVING` to the `ref_competenties` table without a default value. This is not possible if the table is not empty.
    - Modified to have data migration ✅

*/
-- DropForeignKey
ALTER TABLE `ref_competenties` DROP FOREIGN KEY `ref_competenties_ibfk_2`;

-- DropIndex
DROP INDEX `BLOK_ID` ON `ref_competenties`;

-- AlterTable
ALTER TABLE `audit` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `documenten` MODIFY `LEGE_REGEL` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `ONDERSTREEP` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `BOVEN` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_aanwezig_leden` MODIFY `VOORAANMELDING` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_aanwezig_vliegtuigen`
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_agenda` MODIFY `OPENBAAR` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_brandstof` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `oper_daginfo` MODIFY `DDWV` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `CLUB_BEDRIJF` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_dagrapporten` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_diensten` MODIFY `UITBETAALD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_facturen` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_gasten` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_journaal` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_progressie` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_reservering` MODIFY `IS_GEBOEKT` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_rooster` MODIFY `DDWV` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `CLUB_BEDRIJF` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `WINTER_WERK` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_startlijst` MODIFY `DAGNUMMER` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `PAX` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `CHECKSTART` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `INSTRUCTIEVLUCHT` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_tracks` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_transacties` DROP COLUMN `BETAAL_URL`,
    MODIFY `DDWV` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `BETAALD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `oper_winterwerk` MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false;


-- MODIFIED: Alter table, first add the new columns.
-- Then migrate existing data towards it
-- Remove the old.
ALTER TABLE `ref_competenties`
    MODIFY `GELDIGHEID` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,
    ADD COLUMN `OMSCHRIJVING` VARCHAR(75) NOT NULL,
    ADD COLUMN `OUDER_ID` MEDIUMINT UNSIGNED NULL;

UPDATE ref_competenties
SET
    ref_competenties.OUDER_ID = BLOK_ID,
    ref_competenties.OMSCHRIJVING = ref_competenties.ONDERWERP;

ALTER TABLE `ref_competenties`
    DROP COLUMN `BLOK_ID`,
    DROP COLUMN `ONDERWERP`;

-- AlterTable
ALTER TABLE `ref_leden`
    ADD COLUMN `BRANDSTOF_PAS` VARCHAR(25) NULL,
    MODIFY `LIERIST` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LIERIST_IO` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `STARTLEIDER` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `INSTRUCTEUR` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `CIMT` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `DDWV_CREW` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `DDWV_BEHEERDER` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `BEHEERDER` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `STARTTOREN` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `ROOSTER` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `SLEEPVLIEGER` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `RAPPORTEUR` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `GASTENVLIEGER` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `TECHNICUS` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `CLUBBLAD_POST` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `ZELFSTART_ABONNEMENT` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `AUTH` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `STARTVERBOD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `OPGEZEGD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `PRIVACY` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `EMAIL_DAGINFO` TINYINT UNSIGNED NOT NULL DEFAULT false,
                        MODIFY `BUDDY_ID2` MEDIUMINT UNSIGNED NULL,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `ref_types` MODIFY `READ_ONLY` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `ref_types_groepen` MODIFY `READ_ONLY` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `BEDRAG_EENHEDEN` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `ref_vliegtuigen` MODIFY `CLUBKIST` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `TMG` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `ZELFSTART` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `SLEEPKIST` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `INZETBAAR` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `TRAINER` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `VERWIJDERD` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `sys_sync` MODIFY `LAATSTE_AANPASSING` DATETIME(3) NOT NULL;

-- CreateTable
CREATE TABLE `oper_login` (
    `ID` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `LID_ID` MEDIUMINT UNSIGNED NOT NULL,
    `REFRESH_TOKEN` VARCHAR(191) NOT NULL,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `oper_login_LID_ID_key`(`LID_ID`),
    INDEX `LID_ID`(`LID_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `OUDER_ID` ON `ref_competenties`(`OUDER_ID`);

-- AddForeignKey
ALTER TABLE `documenten` ADD CONSTRAINT `documenten_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_login` ADD CONSTRAINT `oper_login_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_aanwezig_leden` ADD CONSTRAINT `oper_aanwezig_leden_VELD_ID_fkey` FOREIGN KEY (`VELD_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_aanwezig_vliegtuigen` ADD CONSTRAINT `oper_aanwezig_vliegtuigen_VELD_ID_fkey` FOREIGN KEY (`VELD_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_gasten` ADD CONSTRAINT `oper_gasten_VELD_ID_fkey` FOREIGN KEY (`VELD_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_competenties` ADD CONSTRAINT `ref_competenties_OUDER_ID_fkey` FOREIGN KEY (`OUDER_ID`) REFERENCES `ref_competenties`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_ibfk_4` FOREIGN KEY (`BUDDY_ID2`) REFERENCES `ref_leden`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_STATUSTYPE_ID_fkey` FOREIGN KEY (`STATUSTYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- Need to align types before adding FK otherwise it will fail!
ALTER TABLE ref_types MODIFY COLUMN GROEP MEDIUMINT UNSIGNED NOT NULL;

-- AddForeignKey
ALTER TABLE `ref_types` ADD CONSTRAINT `ref_types_GROEP_fkey` FOREIGN KEY (`GROEP`) REFERENCES `ref_types_groepen`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
