-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_VLIEGTUIG_ID_fkey` FOREIGN KEY (`VLIEGTUIG_ID`) REFERENCES `ref_vliegtuigen`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_ROLLEND_ID_fkey` FOREIGN KEY (`ROLLEND_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_CATEGORIE_ID_fkey` FOREIGN KEY (`CATEGORIE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
