-- CreateTable
CREATE TABLE `oper_facturen` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `JAAR` INTEGER NULL,
    `LID_ID` INTEGER NOT NULL,
    `NAAM` VARCHAR(255) NOT NULL,
    `LIDNR` VARCHAR(10) NULL,
    `FACTUUR_NUMMER` VARCHAR(25) NULL,
    `CODE` VARCHAR(25) NULL,
    `OMSCHRIJVING` VARCHAR(25) NULL,
    `GEFACTUREERD` FLOAT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    UNIQUE INDEX `oper_facturen_LIDNR_key`(`LIDNR`),
    UNIQUE INDEX `oper_facturen_FACTUUR_NUMMER_key`(`FACTUUR_NUMMER`),
    UNIQUE INDEX `oper_facturen_CODE_key`(`CODE`),
    UNIQUE INDEX `oper_facturen_OMSCHRIJVING_key`(`OMSCHRIJVING`),
    INDEX `oper_facturen_VERWIJDERD_idx`(`VERWIJDERD`),
    INDEX `oper_facturen_JAAR_idx`(`JAAR`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_facturen` ADD CONSTRAINT `oper_facturen_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
