-- CreateTable
CREATE TABLE `ref_vliegtuigen` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `REGISTRATIE` VARCHAR(8) NOT NULL,
    `CALLSIGN` VARCHAR(6) NULL,
    `ZITPLAATSEN` INTEGER NOT NULL DEFAULT 1,
    `CLUBKIST` BOOLEAN NOT NULL DEFAULT false,
    `FLARMCODE` VARCHAR(50) NULL,
    `TYPE_ID` INTEGER NULL,
    `ZELFSTART` BOOLEAN NOT NULL DEFAULT false,
    `TMG` BOOLEAN NOT NULL DEFAULT false,
    `SLEEPKIST` BOOLEAN NOT NULL DEFAULT false,
    `INZETBAAR` BOOLEAN NOT NULL DEFAULT true,
    `VOLGORDE` INTEGER NOT NULL,
    `TRAINER` BOOLEAN NOT NULL DEFAULT false,
    `URL` VARCHAR(1024) NOT NULL,
    `OPMERKINGEN` TEXT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `ref_vliegtuigen_REGISTRATIE_idx`(`REGISTRATIE`),
    INDEX `ref_vliegtuigen_CLUBKIST_idx`(`CLUBKIST`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ref_vliegtuigen` ADD CONSTRAINT `ref_vliegtuigen_TYPE_ID_fkey` FOREIGN KEY (`TYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
