-- CreateTable
CREATE TABLE `oper_agenda` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATETIME(3) NOT NULL,
    `KORT` VARCHAR(191) NULL,
    `OMSCHRIJVING` VARCHAR(191) NULL,
    `OPENBAAR` BOOLEAN NOT NULL DEFAULT true,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `DATUM`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
