-- AddForeignKey
ALTER TABLE `ref_vliegtuigen` ADD CONSTRAINT `ref_vliegtuigen_BEVOEGDHEID_LOKAAL_ID_fkey` FOREIGN KEY (`BEVOEGDHEID_LOKAAL_ID`) REFERENCES `ref_competenties`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_vliegtuigen` ADD CONSTRAINT `ref_vliegtuigen_BEVOEGDHEID_OVERLAND_ID_fkey` FOREIGN KEY (`BEVOEGDHEID_OVERLAND_ID`) REFERENCES `ref_competenties`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
