-- CreateTable
CREATE TABLE `documenten` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VOLGORDE` INTEGER NULL,
    `GROEP_ID` INTEGER NULL,
    `TEKST` VARCHAR(250) NULL,
    `URL` VARCHAR(250) NULL,
    `LID_ID` INTEGER NULL,
    `LEGE_REGEL` BOOLEAN NOT NULL DEFAULT false,
    `ONDERSTREEP` BOOLEAN NOT NULL DEFAULT false,
    `BOVEN` BOOLEAN NOT NULL DEFAULT false,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `documenten` ADD CONSTRAINT `documenten_GROEP_ID_fkey` FOREIGN KEY (`GROEP_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `documenten` ADD CONSTRAINT `documenten_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
