-- CreateTable
CREATE TABLE `oper_diensten` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `ROOSTER_ID` INTEGER NULL,
    `TYPE_DIENST_ID` INTEGER NULL,
    `INGEVOERD_DOOR_ID` INTEGER NOT NULL,
    `UITBETAALD` BOOLEAN NOT NULL DEFAULT false,
    `OPMERKINGEN` TEXT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `oper_diensten_VERWIJDERD_idx`(`VERWIJDERD`),
    INDEX `oper_diensten_DATUM_idx`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_diensten` ADD CONSTRAINT `oper_diensten_ROOSTER_ID_fkey` FOREIGN KEY (`ROOSTER_ID`) REFERENCES `oper_rooster`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_diensten` ADD CONSTRAINT `oper_diensten_TYPE_DIENST_ID_fkey` FOREIGN KEY (`TYPE_DIENST_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_diensten` ADD CONSTRAINT `oper_diensten_INGEVOERD_DOOR_ID_fkey` FOREIGN KEY (`INGEVOERD_DOOR_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
