-- CreateTable
CREATE TABLE `oper_login` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LID_ID` INTEGER NOT NULL,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `LID_ID`(`LID_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_login` ADD CONSTRAINT `oper_login_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
