-- CreateTable
CREATE TABLE `oper_aanwezig_leden` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `LID_ID` INTEGER NOT NULL,
    `VELD_ID` INTEGER NOT NULL,
    `VOORAANMELDING` BOOLEAN NOT NULL DEFAULT false,
    `AANVANG` TIME NOT NULL,
    `VERTREK` TIME NOT NULL,
    `OVERLAND_VLIEGTUIG_ID` INTEGER NOT NULL,
    `VOORKEUR_VLIEGTUIG_TYPE` VARCHAR(256) NULL,
    `TRANSACTIE_ID` INTEGER NOT NULL,
    `OPMERKINGEN` TEXT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `DATUM`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_transacties` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `VLIEGDAG` DATE NOT NULL,
    `LID_ID` INTEGER NOT NULL,
    `INGEVOERD_ID` INTEGER NOT NULL,
    `TYPE_ID` INTEGER NOT NULL,
    `DDWV` BOOLEAN NOT NULL DEFAULT false,
    `BEDRAG` FLOAT NULL,
    `EENHEDEN` FLOAT NULL,
    `SALDO_VOOR` FLOAT NULL,
    `SALDO_NA` FLOAT NULL,
    `EXT_REF` VARCHAR(25) NULL,
    `OMSCHRIJVING` VARCHAR(250) NULL,
    `BETAALD` BOOLEAN NOT NULL DEFAULT false,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `DATUM`(`DATUM`),
    INDEX `VLIEGDAG`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_aanwezig_leden` ADD CONSTRAINT `oper_aanwezig_leden_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_aanwezig_leden` ADD CONSTRAINT `oper_aanwezig_leden_VELD_ID_fkey` FOREIGN KEY (`VELD_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_aanwezig_leden` ADD CONSTRAINT `oper_aanwezig_leden_OVERLAND_VLIEGTUIG_ID_fkey` FOREIGN KEY (`OVERLAND_VLIEGTUIG_ID`) REFERENCES `ref_vliegtuigen`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_aanwezig_leden` ADD CONSTRAINT `oper_aanwezig_leden_TRANSACTIE_ID_fkey` FOREIGN KEY (`TRANSACTIE_ID`) REFERENCES `oper_transacties`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_transacties` ADD CONSTRAINT `oper_transacties_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_transacties` ADD CONSTRAINT `oper_transacties_INGEVOERD_ID_fkey` FOREIGN KEY (`INGEVOERD_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_transacties` ADD CONSTRAINT `oper_transacties_TYPE_ID_fkey` FOREIGN KEY (`TYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
