-- CreateTable
CREATE TABLE `oper_gasten` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VELD_ID` INTEGER NULL,
    `NAAM` VARCHAR(255) NOT NULL,
    `OPMERKINGEN` TEXT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `DATUM_IDX`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_gasten` ADD CONSTRAINT `oper_gasten_VELD_ID_fkey` FOREIGN KEY (`VELD_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
