-- CreateTable
CREATE TABLE `oper_rooster` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `DDWV` BOOLEAN NOT NULL DEFAULT false,
    `CLUB_BEDRIJF` BOOLEAN NOT NULL DEFAULT false,
    `WINTER_WERK` BOOLEAN NOT NULL DEFAULT false,
    `MIN_SLEEPSTART` INTEGER NULL,
    `MIN_LIERSTART` INTEGER NULL,
    `OPMERKINGEN` TEXT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `oper_rooster_VERWIJDERD_idx`(`VERWIJDERD`),
    INDEX `oper_rooster_DATUM_idx`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
