-- CreateTable
CREATE TABLE `oper_brandstof` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LID_ID` INTEGER NOT NULL,
    `NAAM` VARCHAR(255) NOT NULL,
    `BRANDSTOF_TYPE_ID` INTEGER NULL,
    `PRIJS` DECIMAL(6, 2) NULL,
    `BEDRAG` DECIMAL(6, 2) NULL,
    `LITERS` DECIMAL(6, 2) NULL,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `oper_brandstof` ADD CONSTRAINT `oper_brandstof_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_brandstof` ADD CONSTRAINT `oper_brandstof_BRANDSTOF_TYPE_ID_fkey` FOREIGN KEY (`BRANDSTOF_TYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
