-- CreateTable
CREATE TABLE `ref_leden` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAAM` VARCHAR(255) NOT NULL,
    `VOORNAAM` VARCHAR(15) NULL,
    `TUSSENVOEGSEL` VARCHAR(8) NULL,
    `ACHTERNAAM` VARCHAR(30) NULL,
    `ADRES` VARCHAR(50) NULL,
    `POSTCODE` VARCHAR(10) NULL,
    `WOONPLAATS` VARCHAR(50) NULL,
    `TELEFOON` VARCHAR(15) NULL,
    `MOBIEL` VARCHAR(15) NULL,
    `NOODNUMMER` VARCHAR(15) NULL,
    `EMAIL` VARCHAR(45) NULL,
    `LIDNR` VARCHAR(10) NULL,
    `LIDTYPE_ID` INTEGER NULL,
    `STATUSTYPE_ID` INTEGER NULL,
    `ZUSTERCLUB_ID` INTEGER NULL,
    `BUDDY_ID` INTEGER NULL,
    `BUDDY_ID2` INTEGER NULL,
    `LIERIST` BOOLEAN NOT NULL DEFAULT false,
    `LIERIST_IO` BOOLEAN NOT NULL DEFAULT false,
    `STARTLEIDER` BOOLEAN NOT NULL DEFAULT false,
    `INSTRUCTEUR` BOOLEAN NOT NULL DEFAULT false,
    `CIMT` BOOLEAN NOT NULL DEFAULT false,
    `DDWV_CREW` BOOLEAN NOT NULL DEFAULT false,
    `DDWV_BEHEERDER` BOOLEAN NOT NULL DEFAULT false,
    `BEHEERDER` BOOLEAN NOT NULL DEFAULT false,
    `STARTTOREN` BOOLEAN NOT NULL DEFAULT false,
    `ROOSTER` BOOLEAN NOT NULL DEFAULT false,
    `SLEEPVLIEGER` BOOLEAN NOT NULL DEFAULT false,
    `RAPPORTEUR` BOOLEAN NOT NULL DEFAULT false,
    `GASTENVLIEGER` BOOLEAN NOT NULL DEFAULT false,
    `TECHNICUS` BOOLEAN NOT NULL DEFAULT false,
    `CLUBBLAD_POST` BOOLEAN NOT NULL DEFAULT false,
    `ZELFSTART_ABONNEMENT` BOOLEAN NOT NULL DEFAULT false,
    `MEDICAL` DATE NULL,
    `GEBOORTE_DATUM` DATE NULL,
    `INLOGNAAM` VARCHAR(45) NULL,
    `WACHTWOORD` VARCHAR(50) NULL,
    `SECRET` VARCHAR(255) NULL,
    `AUTH` BOOLEAN NOT NULL DEFAULT false,
    `AVATAR` VARCHAR(255) NULL,
    `STARTVERBOD` BOOLEAN NOT NULL DEFAULT false,
    `OPGEZEGD` BOOLEAN NOT NULL DEFAULT false,
    `PRIVACY` BOOLEAN NOT NULL DEFAULT false,
    `SLEUTEL1` VARCHAR(25) NULL,
    `SLEUTEL2` VARCHAR(25) NULL,
    `BEROEP` VARCHAR(50) NULL,
    `KNVVL_LIDNUMMER` VARCHAR(25) NULL,
    `BREVET_NUMMER` VARCHAR(25) NULL,
    `EMAIL_DAGINFO` BOOLEAN NOT NULL DEFAULT false,
    `OPMERKINGEN` TEXT NULL,
    `TEGOED` DOUBLE NOT NULL DEFAULT 0,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `ref_leden_NAAM_idx`(`NAAM`),
    INDEX `ref_leden_LIDTYPE_ID_idx`(`LIDTYPE_ID`),
    INDEX `ref_leden_STATUSTYPE_ID_idx`(`STATUSTYPE_ID`),
    INDEX `ref_leden_STARTLEIDER_idx`(`STARTLEIDER`),
    INDEX `ref_leden_INSTRUCTEUR_idx`(`INSTRUCTEUR`),
    INDEX `ref_leden_LIERIST_idx`(`LIERIST`),
    INDEX `ref_leden_VERWIJDERD_idx`(`VERWIJDERD`),
    INDEX `ref_leden_ZUSTERCLUB_ID_idx`(`ZUSTERCLUB_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_LIDTYPE_ID_fkey` FOREIGN KEY (`LIDTYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_STATUSTYPE_ID_fkey` FOREIGN KEY (`STATUSTYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_ZUSTERCLUB_ID_fkey` FOREIGN KEY (`ZUSTERCLUB_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_BUDDY_ID_fkey` FOREIGN KEY (`BUDDY_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_BUDDY_ID2_fkey` FOREIGN KEY (`BUDDY_ID2`) REFERENCES `ref_leden`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
