-- AlterTable
ALTER TABLE `oper_dagrapporten` MODIFY `INCIDENTEN` TEXT NULL,
    MODIFY `METEO` TEXT NULL,
    MODIFY `DIENSTEN` TEXT NULL,
    MODIFY `VERSLAG` TEXT NULL,
    MODIFY `VLIEGENDMATERIEEL` TEXT NULL,
    MODIFY `ROLLENDMATERIEEL` TEXT NULL;
