-- CreateTable
CREATE TABLE `RefTypes` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TYPEGROEP_ID` INTEGER NOT NULL,
    `CODE` VARCHAR(10) NULL,
    `EXT_REF` VARCHAR(25) NULL,
    `OMSCHRIJVING` VARCHAR(75) NOT NULL,
    `SORTEER_VOLGORDE` TINYINT NULL,
    `READ_ONLY` BOOLEAN NOT NULL DEFAULT false,
    `BEDRAG` DECIMAL(6, 2) NULL,
    `EENHEDEN` DECIMAL(6, 2) NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TYPEGROEP_ID`(`TYPEGROEP_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `RefTypes` ADD CONSTRAINT `RefTypes_TYPEGROEP_ID_fkey` FOREIGN KEY (`TYPEGROEP_ID`) REFERENCES `RefTypesGroepen`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
