-- CreateTable
CREATE TABLE `Audit` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `LID_ID` INTEGER NOT NULL,
    `TABEL` VARCHAR(25) NULL,
    `TABEL_NAAM` VARCHAR(25) NULL,
    `ACTIE` VARCHAR(15) NULL,
    `OBJECT_ID` INTEGER NULL,
    `VOOR` TEXT NULL,
    `DATA` TEXT NULL,
    `RESULTAAT` TEXT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `documenten` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VOLGORDE` INTEGER NULL,
    `GROEP_ID` INTEGER NULL,
    `TEKST` VARCHAR(250) NULL,
    `URL` VARCHAR(250) NULL,
    `LID_ID` INTEGER NULL,
    `LEGE_REGEL` BOOLEAN NOT NULL DEFAULT false,
    `ONDERSTREEP` BOOLEAN NOT NULL DEFAULT false,
    `BOVEN` BOOLEAN NOT NULL DEFAULT false,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_login` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LID_ID` INTEGER NOT NULL,
    `REFRESH_TOKEN` VARCHAR(191) NOT NULL,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `oper_login_LID_ID_key`(`LID_ID`),
    INDEX `LID_ID`(`LID_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_agenda` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATETIME(3) NOT NULL,
    `KORT` VARCHAR(191) NULL,
    `OMSCHRIJVING` VARCHAR(191) NULL,
    `OPENBAAR` BOOLEAN NOT NULL DEFAULT true,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `DATUM`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_brandstof` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LID_ID` INTEGER NOT NULL,
    `NAAM` VARCHAR(255) NOT NULL,
    `TIJDSTIP` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `BRANDSTOF_TYPE_ID` INTEGER NULL,
    `PRIJS` FLOAT NULL,
    `BEDRAG` FLOAT NULL,
    `LITERS` FLOAT NULL,
    `EXT_REF` VARCHAR(50) NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_daginfo` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VELD_ID` INTEGER NOT NULL,
    `BAAN_ID` INTEGER NOT NULL,
    `STARTMETHODE_ID` INTEGER NOT NULL,
    `VELD_ID2` INTEGER NOT NULL,
    `BAAN_ID2` INTEGER NOT NULL,
    `STARTMETHODE_ID2` INTEGER NOT NULL,
    `CLUB_BEDRIJF` BOOLEAN NOT NULL DEFAULT false,
    `DDWV` BOOLEAN NOT NULL DEFAULT false,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_dagrapporten` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `VELD_ID` INTEGER NOT NULL,
    `INGEVOERD_ID` INTEGER NOT NULL,
    `INCIDENTEN` VARCHAR(191) NULL,
    `METEO` VARCHAR(191) NULL,
    `DIENSTEN` VARCHAR(191) NULL,
    `VERSLAG` VARCHAR(191) NULL,
    `ROLLENMATERIEEL` VARCHAR(191) NULL,
    `VLIEGENDMATERIEEL` VARCHAR(191) NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `DATUM`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_journaal` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VLIEGTUIG_ID` INTEGER NULL,
    `ROLLEND_ID` INTEGER NULL,
    `TITEL` VARCHAR(75) NOT NULL,
    `OMSCHRIJVING` TEXT NULL,
    `CATEGORIE_ID` INTEGER NULL,
    `STATUS_ID` INTEGER NULL,
    `MELDER_ID` INTEGER NULL,
    `TECHNICUS_ID` INTEGER NULL,
    `AFGETEKEND_ID` INTEGER NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `oper_winterwerk` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DATUM` DATE NOT NULL,
    `AANVANG` TIME NOT NULL,
    `EINDE` TIME NOT NULL,
    `OPMERKINGEN` VARCHAR(191) NULL,
    `LID_ID` INTEGER NOT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL,

    INDEX `DATUM`(`DATUM`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ref_competenties` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `VOLGORDE` INTEGER NULL,
    `LEERFASE_ID` INTEGER NULL,
    `OUDER_ID` INTEGER NULL,
    `BLOK` VARCHAR(7) NULL,
    `OMSCHRIJVING` VARCHAR(75) NOT NULL,
    `DOCUMENTATIE` VARCHAR(75) NULL,
    `GELDIGHEID` BOOLEAN NOT NULL DEFAULT false,
    `SCORE` BOOLEAN NOT NULL DEFAULT false,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ref_leden` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAAM` VARCHAR(255) NOT NULL,
    `VOORNAAM` VARCHAR(15) NULL,
    `TUSSENVOEGSEL` VARCHAR(8) NULL,
    `ACHTERNAAM` VARCHAR(30) NULL,
    `ADRES` VARCHAR(50) NULL,
    `POSTCODE` VARCHAR(10) NULL,
    `WOONPLAATS` VARCHAR(50) NULL,
    `TELEFOON` VARCHAR(15) NULL,
    `MOBIEL` VARCHAR(15) NULL,
    `NOODNUMMER` VARCHAR(15) NULL,
    `EMAIL` VARCHAR(45) NULL,
    `LIDNR` VARCHAR(10) NULL,
    `LIDTYPE_ID` INTEGER NULL,
    `STATUSTYPE_ID` INTEGER NULL,
    `ZUSTERCLUB_ID` INTEGER NULL,
    `BUDDY_ID` INTEGER NULL,
    `BUDDY_ID2` INTEGER NULL,
    `LIERIST` BOOLEAN NOT NULL DEFAULT false,
    `LIERIST_IO` BOOLEAN NOT NULL DEFAULT false,
    `STARTLEIDER` BOOLEAN NOT NULL DEFAULT false,
    `INSTRUCTEUR` BOOLEAN NOT NULL DEFAULT false,
    `CIMT` BOOLEAN NOT NULL DEFAULT false,
    `DDWV_CREW` BOOLEAN NOT NULL DEFAULT false,
    `DDWV_BEHEERDER` BOOLEAN NOT NULL DEFAULT false,
    `BEHEERDER` BOOLEAN NOT NULL DEFAULT false,
    `STARTTOREN` BOOLEAN NOT NULL DEFAULT false,
    `ROOSTER` BOOLEAN NOT NULL DEFAULT false,
    `SLEEPVLIEGER` BOOLEAN NOT NULL DEFAULT false,
    `RAPPORTEUR` BOOLEAN NOT NULL DEFAULT false,
    `GASTENVLIEGER` BOOLEAN NOT NULL DEFAULT false,
    `TECHNICUS` BOOLEAN NOT NULL DEFAULT false,
    `CLUBBLAD_POST` BOOLEAN NOT NULL DEFAULT false,
    `ZELFSTART_ABONNEMENT` BOOLEAN NOT NULL DEFAULT false,
    `MEDICAL` DATE NULL,
    `GEBOORTE_DATUM` DATE NULL,
    `INLOGNAAM` VARCHAR(45) NULL,
    `WACHTWOORD` VARCHAR(50) NULL,
    `SECRET` VARCHAR(255) NULL,
    `AUTH` BOOLEAN NOT NULL DEFAULT false,
    `AVATAR` VARCHAR(255) NULL,
    `STARTVERBOD` BOOLEAN NOT NULL DEFAULT false,
    `OPGEZEGD` BOOLEAN NOT NULL DEFAULT false,
    `PRIVACY` BOOLEAN NOT NULL DEFAULT false,
    `SLEUTEL1` VARCHAR(25) NULL,
    `SLEUTEL2` VARCHAR(25) NULL,
    `BRANDSTOF_PAS` VARCHAR(25) NULL,
    `BEROEP` VARCHAR(50) NULL,
    `KNVVL_LIDNUMMER` VARCHAR(25) NULL,
    `BREVET_NUMMER` VARCHAR(25) NULL,
    `EMAIL_DAGINFO` BOOLEAN NOT NULL DEFAULT false,
    `OPMERKINGEN` TEXT NULL,
    `TEGOED` DOUBLE NOT NULL DEFAULT 0,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `ref_leden_LIDNR_key`(`LIDNR`),
    UNIQUE INDEX `ref_leden_INLOGNAAM_key`(`INLOGNAAM`),
    INDEX `ref_leden_NAAM_idx`(`NAAM`),
    INDEX `ref_leden_LIDTYPE_ID_idx`(`LIDTYPE_ID`),
    INDEX `ref_leden_STATUSTYPE_ID_idx`(`STATUSTYPE_ID`),
    INDEX `ref_leden_STARTLEIDER_idx`(`STARTLEIDER`),
    INDEX `ref_leden_INSTRUCTEUR_idx`(`INSTRUCTEUR`),
    INDEX `ref_leden_LIERIST_idx`(`LIERIST`),
    INDEX `ref_leden_VERWIJDERD_idx`(`VERWIJDERD`),
    INDEX `ref_leden_ZUSTERCLUB_ID_idx`(`ZUSTERCLUB_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ref_types` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TYPEGROEP_ID` INTEGER NOT NULL,
    `CODE` VARCHAR(10) NULL,
    `EXT_REF` VARCHAR(25) NULL,
    `OMSCHRIJVING` VARCHAR(75) NOT NULL,
    `SORTEER_VOLGORDE` TINYINT NULL,
    `READ_ONLY` BOOLEAN NOT NULL DEFAULT false,
    `BEDRAG` FLOAT NULL,
    `EENHEDEN` FLOAT NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TYPEGROEP_ID`(`TYPEGROEP_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ref_types_groepen` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CODE` VARCHAR(10) NULL,
    `EXT_REF` VARCHAR(25) NULL,
    `OMSCHRIJVING` VARCHAR(75) NOT NULL,
    `SORTEER_VOLGORDE` SMALLINT NULL,
    `READ_ONLY` BOOLEAN NOT NULL DEFAULT false,
    `BEDRAG_EENHEDEN` BOOLEAN NOT NULL DEFAULT false,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ref_vliegtuigen` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `REGISTRATIE` VARCHAR(8) NOT NULL,
    `CALLSIGN` VARCHAR(6) NULL,
    `ZITPLAATSEN` INTEGER NOT NULL DEFAULT 1,
    `CLUBKIST` BOOLEAN NOT NULL DEFAULT false,
    `FLARMCODE` VARCHAR(50) NULL,
    `TYPE_ID` INTEGER NULL,
    `ZELFSTART` BOOLEAN NOT NULL DEFAULT false,
    `TMG` BOOLEAN NOT NULL DEFAULT false,
    `SLEEPKIST` BOOLEAN NOT NULL DEFAULT false,
    `INZETBAAR` BOOLEAN NOT NULL DEFAULT true,
    `VOLGORDE` INTEGER NULL,
    `TRAINER` BOOLEAN NOT NULL DEFAULT false,
    `URL` VARCHAR(1024) NULL,
    `OPMERKINGEN` TEXT NULL,
    `BEVOEGDHEID_LOKAAL_ID` INTEGER NULL,
    `BEVOEGDHEID_OVERLAND_ID` INTEGER NULL,
    `VERWIJDERD` BOOLEAN NOT NULL DEFAULT false,
    `LAATSTE_AANPASSING` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `ref_vliegtuigen_REGISTRATIE_idx`(`REGISTRATIE`),
    INDEX `ref_vliegtuigen_CLUBKIST_idx`(`CLUBKIST`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Audit` ADD CONSTRAINT `Audit_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `documenten` ADD CONSTRAINT `documenten_GROEP_ID_fkey` FOREIGN KEY (`GROEP_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `documenten` ADD CONSTRAINT `documenten_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_login` ADD CONSTRAINT `oper_login_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_brandstof` ADD CONSTRAINT `oper_brandstof_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_brandstof` ADD CONSTRAINT `oper_brandstof_BRANDSTOF_TYPE_ID_fkey` FOREIGN KEY (`BRANDSTOF_TYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_VELD_ID_fkey` FOREIGN KEY (`VELD_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_BAAN_ID_fkey` FOREIGN KEY (`BAAN_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_STARTMETHODE_ID_fkey` FOREIGN KEY (`STARTMETHODE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_VELD_ID2_fkey` FOREIGN KEY (`VELD_ID2`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_BAAN_ID2_fkey` FOREIGN KEY (`BAAN_ID2`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_daginfo` ADD CONSTRAINT `oper_daginfo_STARTMETHODE_ID2_fkey` FOREIGN KEY (`STARTMETHODE_ID2`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_dagrapporten` ADD CONSTRAINT `oper_dagrapporten_VELD_ID_fkey` FOREIGN KEY (`VELD_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_dagrapporten` ADD CONSTRAINT `oper_dagrapporten_INGEVOERD_ID_fkey` FOREIGN KEY (`INGEVOERD_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_VLIEGTUIG_ID_fkey` FOREIGN KEY (`VLIEGTUIG_ID`) REFERENCES `ref_vliegtuigen`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_ROLLEND_ID_fkey` FOREIGN KEY (`ROLLEND_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_CATEGORIE_ID_fkey` FOREIGN KEY (`CATEGORIE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_STATUS_ID_fkey` FOREIGN KEY (`STATUS_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_MELDER_ID_fkey` FOREIGN KEY (`MELDER_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_TECHNICUS_ID_fkey` FOREIGN KEY (`TECHNICUS_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_journaal` ADD CONSTRAINT `oper_journaal_AFGETEKEND_ID_fkey` FOREIGN KEY (`AFGETEKEND_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `oper_winterwerk` ADD CONSTRAINT `oper_winterwerk_LID_ID_fkey` FOREIGN KEY (`LID_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_competenties` ADD CONSTRAINT `ref_competenties_LEERFASE_ID_fkey` FOREIGN KEY (`LEERFASE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_competenties` ADD CONSTRAINT `ref_competenties_OUDER_ID_fkey` FOREIGN KEY (`OUDER_ID`) REFERENCES `ref_competenties`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_LIDTYPE_ID_fkey` FOREIGN KEY (`LIDTYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_STATUSTYPE_ID_fkey` FOREIGN KEY (`STATUSTYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_ZUSTERCLUB_ID_fkey` FOREIGN KEY (`ZUSTERCLUB_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_BUDDY_ID_fkey` FOREIGN KEY (`BUDDY_ID`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_leden` ADD CONSTRAINT `ref_leden_BUDDY_ID2_fkey` FOREIGN KEY (`BUDDY_ID2`) REFERENCES `ref_leden`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_types` ADD CONSTRAINT `ref_types_TYPEGROEP_ID_fkey` FOREIGN KEY (`TYPEGROEP_ID`) REFERENCES `ref_types_groepen`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_vliegtuigen` ADD CONSTRAINT `ref_vliegtuigen_TYPE_ID_fkey` FOREIGN KEY (`TYPE_ID`) REFERENCES `ref_types`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_vliegtuigen` ADD CONSTRAINT `ref_vliegtuigen_BEVOEGDHEID_LOKAAL_ID_fkey` FOREIGN KEY (`BEVOEGDHEID_LOKAAL_ID`) REFERENCES `ref_competenties`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ref_vliegtuigen` ADD CONSTRAINT `ref_vliegtuigen_BEVOEGDHEID_OVERLAND_ID_fkey` FOREIGN KEY (`BEVOEGDHEID_OVERLAND_ID`) REFERENCES `ref_competenties`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
