name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
        name: Install Dependencies

      - run: npm run build
        name: Build

      - run: npm run lint
        name: Lint